- name: update the the apt manager
  apt:
    update_cache: yes

- name: install {{web}} server
  apt:
    name: "{{web}}"
    state: present
- name: start the service
  service:
    name: "{{web}}"
    state: started
    enabled: yes
- name: copy the html file
  copy:
    src: index.html
    dest: /var/www/html
  notify: restart apache
